# Generated by Django 3.1.5 on 2021-03-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210306_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('address1', models.TextField(default='')),
                ('address2', models.TextField(default='')),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('zipCode', models.CharField(default='', max_length=10)),
                ('phoneNum', models.CharField(default='', max_length=10)),
                ('altPhoneNum', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
