# Generated by Django 3.1.5 on 2021-03-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210311_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address2',
            new_name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lastName',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
