# Generated by Django 3.1.5 on 2021-03-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210311_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackOrder',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=500)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
